### ISSUE TITLE
Links to chapters do not work

### ISSUE THREAD

**Issue by beardhatcode** [dodona-edu/programmeursleerling#321]
Links to chapters and sections on https://dodona.ugent.be/en/activities/249847267 don't work

https://github.com/dodona-edu/programmeursleerling/blob/4555b01823c3761c5a7b96f3f548bc37ec785a9d/chapters/01%20introduction/01%20how%20to%20use%20this%20book/description/description.en.md?plain=1#L52

**Comment by chvp** [comment]
I think these should be links to different exercises/reading activities, but we don't really have support for that.

**Comment by pdawyndt** [comment]
These are the original links that were taken over from the original book (online version). Since the links point to book chapters as a whole or individual sections in the book, in the Dodona they should become links to series or exercises in the course. When preparing the book for Dodona, we haven't touched these links, since Dodona does not yet support stable links to series/exercises in the course, that would remain valid after copying the course.
